import type {
  ArtifactVersion,
  BuildJob,
  DashboardStats,
  KnowledgeBase,
  KnowledgeBaseSourceBinding,
  MCPKBStatus,
  MCPQueryResult,
  Project,
  Release,
  Source,
} from "./types";

export const MOCK_PROJECTS: Project[] = [
  { id: "proj_delivery_alpha", name: "Delivery Alpha", description: "Core delivery platform" },
  { id: "proj_payment_beta", name: "Payment Beta", description: "Payment processing services" },
];

export const MOCK_SOURCES: Source[] = [
  {
    id: "src_checkout_service",
    project_id: "proj_delivery_alpha",
    name: "checkout-service",
    type: "github_repo",
    status: "active",
    source_ref: "acme/checkout-service",
    description: "Checkout service source repository",
    auth_config: { credential_ref: "github-app-prod" },
    sync_strategy: "webhook",
    include_rules: ["src/**"],
    exclude_rules: ["tmp/**", "*.test.ts"],
    normalization_options: { preserve_metadata: true },
    last_synced_at: "2026-05-19T09:30:00Z",
    created_at: "2026-05-10T08:00:00Z",
    updated_at: "2026-05-19T09:30:00Z",
  },
  {
    id: "src_payment_api",
    project_id: "proj_delivery_alpha",
    name: "payment-api",
    type: "github_repo",
    status: "active",
    source_ref: "acme/payment-api",
    description: "Payment API service",
    auth_config: { credential_ref: "github-app-prod" },
    sync_strategy: "webhook",
    include_rules: ["src/**", "docs/**"],
    exclude_rules: ["tmp/**"],
    normalization_options: {},
    last_synced_at: "2026-05-19T08:15:00Z",
    created_at: "2026-05-12T10:00:00Z",
    updated_at: "2026-05-19T08:15:00Z",
  },
  {
    id: "src_docs_site",
    project_id: "proj_delivery_alpha",
    name: "delivery-docs",
    type: "doc_site",
    status: "syncing",
    source_ref: "https://docs.acme.internal/delivery",
    description: "Internal delivery documentation site",
    auth_config: {},
    sync_strategy: "polling",
    include_rules: ["**/*.md"],
    exclude_rules: [],
    normalization_options: { strip_html: true },
    last_synced_at: null,
    created_at: "2026-05-15T14:00:00Z",
    updated_at: "2026-05-19T10:00:00Z",
  },
];

export const MOCK_KNOWLEDGE_BASES: KnowledgeBase[] = [
  {
    id: "kb_checkout_core",
    project_id: "proj_delivery_alpha",
    name: "Checkout Core Knowledge Base",
    status: "ready",
    visibility: "org_shared",
    active_release_id: "rel_2026_05_19_001",
    description: "Knowledge base for checkout domain code and docs",
    release_policy: { activation_mode: "auto_activate" },
    llm_backend: "claude",
    llm_api_key_ref: null,
    llm_model_override: null,
    llm_extraction_budget: null,
    llm_base_url_override: null,
    created_at: "2026-05-16T09:00:00Z",
    updated_at: "2026-05-19T10:30:00Z",
  },
  {
    id: "kb_payment_services",
    project_id: "proj_delivery_alpha",
    name: "Payment Services KB",
    status: "building",
    visibility: "org_shared",
    active_release_id: null,
    description: "Payment processing knowledge base",
    release_policy: { activation_mode: "manual_review" },
    llm_backend: "openai",
    llm_api_key_ref: "env:OPENAI_API_KEY",
    llm_model_override: "gpt-4o",
    llm_extraction_budget: 60000,
    llm_base_url_override: null,
    created_at: "2026-05-17T11:00:00Z",
    updated_at: "2026-05-19T10:25:00Z",
  },
  {
    id: "kb_platform_arch",
    project_id: "proj_delivery_alpha",
    name: "Platform Architecture KB",
    status: "empty",
    visibility: "private",
    active_release_id: null,
    description: "Architecture decision records and diagrams",
    release_policy: { activation_mode: "manual_review" },
    llm_backend: null,
    llm_api_key_ref: null,
    llm_model_override: null,
    llm_extraction_budget: null,
    llm_base_url_override: null,
    created_at: "2026-05-18T16:00:00Z",
    updated_at: "2026-05-18T16:00:00Z",
  },
];

export const MOCK_BINDINGS: KnowledgeBaseSourceBinding[] = [
  {
    id: "bind_checkout_repo_main",
    knowledge_base_id: "kb_checkout_core",
    source_id: "src_checkout_service",
    binding_status: "active",
    scope_override: { tracked_branches: ["main"] },
    include_rules_override: ["src/**"],
    exclude_rules_override: ["tmp/**"],
    priority: 100,
  },
  {
    id: "bind_payment_repo_main",
    knowledge_base_id: "kb_payment_services",
    source_id: "src_payment_api",
    binding_status: "active",
    scope_override: { tracked_branches: ["main", "develop"] },
    include_rules_override: ["src/**", "docs/**"],
    exclude_rules_override: [],
    priority: 100,
  },
];

export const MOCK_BUILD_JOBS: BuildJob[] = [
  {
    job_id: "job_2026_05_19_0021",
    knowledge_base_id: "kb_checkout_core",
    build_type: "incremental_update",
    status: "completed",
    release_id: "rel_2026_05_19_001",
    triggered_by: "manual",
    reason: "Sync latest checkout service changes",
    started_at: "2026-05-19T10:00:00Z",
    finished_at: "2026-05-19T10:30:00Z",
    error_summary: null,
    stages: [
      { name: "resolve_job_context", status: "completed", started_at: "2026-05-19T10:00:00Z", finished_at: "2026-05-19T10:01:00Z", log: "Resolved 1 source binding." },
      { name: "materialize_sources", status: "completed", started_at: "2026-05-19T10:01:00Z", finished_at: "2026-05-19T10:05:00Z", log: "Cloned acme/checkout-service @ main." },
      { name: "normalize_inputs", status: "completed", started_at: "2026-05-19T10:05:00Z", finished_at: "2026-05-19T10:08:00Z", log: "Normalized 247 files." },
      { name: "run_graphify", status: "completed", started_at: "2026-05-19T10:08:00Z", finished_at: "2026-05-19T10:22:00Z", log: "Generated graph with 1,203 nodes and 3,456 edges." },
      { name: "enhance_obsidian", status: "completed", started_at: "2026-05-19T10:22:00Z", finished_at: "2026-05-19T10:26:00Z", log: "Enhanced vault with backlinks and metadata." },
      { name: "register_release", status: "completed", started_at: "2026-05-19T10:26:00Z", finished_at: "2026-05-19T10:28:00Z", log: "Registered release rel_2026_05_19_001." },
      { name: "activate_or_roll_back", status: "completed", started_at: "2026-05-19T10:28:00Z", finished_at: "2026-05-19T10:30:00Z", log: "Release activated as active." },
    ],
  },
  {
    job_id: "job_2026_05_19_0022",
    knowledge_base_id: "kb_payment_services",
    build_type: "full_rebuild",
    status: "running",
    release_id: null,
    triggered_by: "webhook",
    reason: "New source binding added",
    started_at: "2026-05-19T10:25:00Z",
    finished_at: null,
    error_summary: null,
    stages: [
      { name: "resolve_job_context", status: "completed", started_at: "2026-05-19T10:25:00Z", finished_at: "2026-05-19T10:26:00Z", log: "Resolved 1 source binding." },
      { name: "materialize_sources", status: "completed", started_at: "2026-05-19T10:26:00Z", finished_at: "2026-05-19T10:31:00Z", log: "Cloned acme/payment-api @ main." },
      { name: "normalize_inputs", status: "running", started_at: "2026-05-19T10:31:00Z", finished_at: null, log: "Normalizing source files..." },
      { name: "run_graphify", status: "pending", started_at: null, finished_at: null, log: "" },
      { name: "enhance_obsidian", status: "pending", started_at: null, finished_at: null, log: "" },
      { name: "register_release", status: "pending", started_at: null, finished_at: null, log: "" },
      { name: "activate_or_roll_back", status: "pending", started_at: null, finished_at: null, log: "" },
    ],
  },
  {
    job_id: "job_2026_05_18_0018",
    knowledge_base_id: "kb_checkout_core",
    build_type: "full_rebuild",
    status: "failed",
    release_id: null,
    triggered_by: "manual",
    reason: "Initial full build attempt",
    started_at: "2026-05-18T15:00:00Z",
    finished_at: "2026-05-18T15:12:00Z",
    error_summary: "graphify CLI exited with code 1: duplicate node ids in source tree",
    stages: [
      { name: "resolve_job_context", status: "completed", started_at: "2026-05-18T15:00:00Z", finished_at: "2026-05-18T15:01:00Z", log: "Resolved 2 source bindings." },
      { name: "materialize_sources", status: "completed", started_at: "2026-05-18T15:01:00Z", finished_at: "2026-05-18T15:06:00Z", log: "Materialized 2 sources." },
      { name: "normalize_inputs", status: "completed", started_at: "2026-05-18T15:06:00Z", finished_at: "2026-05-18T15:09:00Z", log: "Normalized 512 files." },
      { name: "run_graphify", status: "failed", started_at: "2026-05-18T15:09:00Z", finished_at: "2026-05-18T15:12:00Z", log: "ERROR: duplicate node ids detected in source tree." },
      { name: "enhance_obsidian", status: "pending", started_at: null, finished_at: null, log: "" },
      { name: "register_release", status: "pending", started_at: null, finished_at: null, log: "" },
      { name: "activate_or_roll_back", status: "pending", started_at: null, finished_at: null, log: "" },
    ],
  },
];

export const MOCK_RELEASES: Release[] = [
  {
    id: "rel_2026_05_19_001",
    knowledge_base_id: "kb_checkout_core",
    build_job_id: "job_2026_05_19_0021",
    version: "1.0.0",
    status: "active",
    artifact_status: { graph: "ready", vault: "ready", obsidian_vault: "ready", metadata_index: "ready" },
    created_at: "2026-05-19T10:28:00Z",
  },
  {
    id: "rel_2026_05_17_001",
    knowledge_base_id: "kb_checkout_core",
    build_job_id: "job_2026_05_17_0015",
    version: "0.9.0",
    status: "superseded",
    artifact_status: { graph: "ready", vault: "ready", obsidian_vault: "ready", metadata_index: "ready" },
    created_at: "2026-05-17T14:00:00Z",
  },
];

export const MOCK_ARTIFACTS: ArtifactVersion[] = [
  {
    id: "art_graph_rel_001",
    release_id: "rel_2026_05_19_001",
    artifact_type: "graph",
    artifact_status: "ready",
    artifact_path: "/data/artifacts/kb_checkout_core/rel_2026_05_19_001/graph.html",
    artifact_meta: { node_count: 1203, edge_count: 3456, format: "html" },
  },
  {
    id: "art_vault_rel_001",
    release_id: "rel_2026_05_19_001",
    artifact_type: "obsidian_vault",
    artifact_status: "ready",
    artifact_path: "/data/artifacts/kb_checkout_core/rel_2026_05_19_001/vault/",
    artifact_meta: { note_count: 847, attachment_count: 32 },
  },
  {
    id: "art_index_rel_001",
    release_id: "rel_2026_05_19_001",
    artifact_type: "metadata_index",
    artifact_status: "ready",
    artifact_path: "/data/artifacts/kb_checkout_core/rel_2026_05_19_001/index.json",
    artifact_meta: { indexed_entities: 5200 },
  },
];

export const MOCK_MCP_STATUS: MCPKBStatus = {
  kb_id: "kb_checkout_core",
  status: "ready",
  active_release_id: "rel_2026_05_19_001",
  graph_status: "ready",
  vault_status: "ready",
  last_build_job_id: "job_2026_05_19_0021",
  last_build_at: "2026-05-19T10:30:00Z",
};

export const MOCK_MCP_QUERY_RESULT: MCPQueryResult = {
  kb_id: "kb_checkout_core",
  release_id: "rel_2026_05_19_001",
  updated_at: "2026-05-19T10:42:00Z",
  answer: "The CheckoutService class in src/services/checkout.ts handles order validation, payment processing, and inventory reservation. It depends on PaymentGateway and InventoryManager. The service follows the saga pattern for distributed transaction management.",
  source_locations: [
    "src/services/checkout.ts:45-120",
    "src/types/checkout.ts:12-34",
    "docs/checkout-flow.md",
  ],
  artifact_refs: {
    graph: "/data/artifacts/kb_checkout_core/rel_2026_05_19_001/graph.html",
    vault: "/data/artifacts/kb_checkout_core/rel_2026_05_19_001/vault/",
  },
};

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  project_count: 1,
  source_count: 3,
  kb_count: 3,
  active_build_count: 1,
  recent_builds: MOCK_BUILD_JOBS.slice(0, 5),
  recent_releases: MOCK_RELEASES.slice(0, 5),
};
